#!/usr/bin/env ruby
require_relative '../lib/recycle'
require_relative '../lib/recycle/list'

require 'fileutils'
require 'rubygems'
require 'yaml'
require 'commander/import'

program :name, 'Recycle'
program :version, Recycle::VERSION
program :description, 'A command for storing frequently used commands.'

default_command :help

RECYCLE_HOME   = File.join(ENV['RECYCLE_ROOT'] || Dir.home, '.recycle')
DATA_FILE      = File.join(RECYCLE_HOME, 'data.yml')
RECYCLE_CONFIG = File.exists?(DATA_FILE) ? YAML.load_file(DATA_FILE) : {}

command :init do |cmd|
  cmd.syntax = 'recycle init'
  cmd.description = 'Setup the recycle storage directory. RECYCLE_ROOT env variable to change destination'
  cmd.action do
    FileUtils.mkdir_p(RECYCLE_HOME)
  end
end

command :list do |cmd|
  cmd.syntax = 'recycle list <filter>'
  cmd.description = 'List all recycle entires. filter can be "dir" or "cmd"'
  cmd.action do |args|
    output = ''
    
    show_commands    = args.length.zero? || args.include?('cmd')
    show_directories = args.length.zero? || args.include?('dir')
    
    puts Recycle::List.render_section('Commands', RECYCLE_CONFIG.fetch('commands', {})) if show_commands
    puts Recycle::List.render_section('Directories', RECYCLE_CONFIG.fetch('directories', {})) if show_directories

    unless show_commands || show_directories
      output << <<~DOC
      Usage
      ================================================================================

        recycle list     - Lists out all entities
        recycle list dir - Lists out directory entities
        recycle list cmd - Lists out command entities
      DOC
    end
    puts output
  end
end

